         <form action="/search/" method="get" id="search" class="indexSearch" name="search">
        
        <div class="limits">
        <div class="limitColumn">
        <label> <input name="searchtype" class="searchtype" value="X" type="radio"> Keyword </label> 
        <label> <input name="searchtype" class="searchtype" value="t" type="radio"> Title begins with </label>
        </div>
        <div class="limitColumn">
        <label> <input name="searchtype" class="searchtype" value="s" type="radio"> Journal & Newspapers title begins with </label>
        <label> <input name="searchtype" class="searchtype" value="a" checked="checked" type="radio"> Author (last name first) </label>
        </div>
        </div>
        
        <div class="clear"></div>
        
<!--{nosort}-->
        
        <div class="searchBox"><input name="searcharg" value="" id="searcharg" class="text" type="text">
        
<!--{scope}-->
        
        
        <input value="Search" type="submit"> </label></div>
        
        </form>
 
        <p><strong>Search Tips for Author</strong> People: Type LAST NAME, FIRST NAME <em>Examples:</em></p>
        <ul>
          <li><em>Powell, Lawrence Clark</em></li>
        </ul>
        Corporate Body or Conference name: Type as much of the EXACT NAME as you know. Start at the beginning. <em>Examples:</em>
        <ul>
          <li><em>Amnesty International</em></li>
        </ul>