        <p><strong>Search Tips for Author</strong></p>
        People: Type <strong>LAST NAME, FIRST NAME</strong>
        <p><em>Example:</em></p>
        <ul>
          <li><em>Powell, Lawrence Clark</em></li>
        </ul>
       <p> Corporate Body or Conference name: Type as much of the <strong>EXACT NAME</strong> as you know. Start at the beginning.</p>
       <p><em>Example:</em></p>
        <ul>
          <li><em>Amnesty International</em></li>
        </ul>