        <p><strong>Search Tips for Author</strong></p>
        People: Type LAST NAME, FIRST NAME <em>Examples:</em>
        <ul>
          <li><em>Powell, Lawrence Clark</em></li>
        </ul>
        Corporate Body or Conference name: Type as much of the EXACT NAME as you know. Start at the beginning. <em>Examples:</em>
        <ul>
          <li><em>Amnesty International</em></li>
        </ul>