  <p><strong>B&#250;squeda por autor</strong></p>
        Indique el <strong>apellido del autor o del artista.</strong>
        <p><em>Ejemplo:</em></p>
        <ul>
          <li><em>Powell, Lawrence Clark</em></li>
        </ul>
       <p> Tambi&#233;n puede indicar el <strong>nombre</strong> de una organizaci&#243;n u organismo gubernamental.</p>
       <p><em>Ejemplo:</em></p>
        <ul>
          <li><em>Amnesty International</em></li>
        </ul>
