        <p><strong>Search Tips for Subjects (Library of Congress)</strong></p>
        <p>Search Library of Congress Subject Headings for people, topics, or events.</p>
        <p><em>Examples:</em></p>
        <ul>
          <li><em>Sports for women</em></li>
          <li><em>Automobiles</em></li>
          <li><em>Wilder, Laura Ingalls</em></li>
          </ul>
        <p>If your search is unsuccessful, try a Keyword search. </p>