        <p><strong>B&#250;squeda por materia (Library of Congress)</strong></p>
        <p>Indique la materia que quiere encontrar.</p>
        <p><em>Ejemplos:</em></p>
        <ul>
          <li><em>Sports for women</em></li>
          <li><em>Automobiles</em></li>
          <li><em>Wilder, Laura Ingalls</em></li>
          </ul>
        <p>Si su b&#250;squeda no tiene &#233;xito, pruebe una b&#250;squeda de palabra clave. </p>