        <p><strong>Search Tips for Dewey/Other Call Number searches</strong></p>
        <p>Search for items by Dewey Decimal Call Numbers and locally assigned call numbers.  Type as much of the call number as you know.</p>
        <p><em>Examples:</em></p>
        <ul>
          <li><em>Thesis T 3045</em></li>
          <li><em>Film Book 0001 1987</em></li>
          <li><em>980.5 j826 353.9</em></li>
          <li><em>353.9</em></li>
        </ul>