        <p><strong>Consejos sobre b&#250;squedas por n&#250;mero de clasificaci&#243;n (Dewey/Otros)</strong></p>
        <p>Escriba  usted  todo lo que pueda del número de clasificación que  más conozca.</p>
        <p><em>Ejemplos:</em></p>
        <ul>
          <li><em>Thesis T 3045</em></li>
          <li><em>Film Book 0001 1987</em></li>
          <li><em>980.5 j826 353.9</em></li>
          <li><em>353.9</em></li>
        </ul>