        <p><strong>Consejos sobre b&#250;squedas por n&#250;mero de clasificaci&#243;n (medicina)</strong></p>
        <p>Busca usted &#237;tems por el n&#250;mero de clasificaci&#243;n de la Biblioteca Nacional de Medicina (NLM). Escriba  usted  todo lo que pueda del n&#250;mero de clasificaci&#243;n que  m&#225;s conozca.</p>
        <p><em>Ejemplos:</em></p>
        <ul>
          <li><em>QZ4 T483L</em></li>
        </ul>