        <p><strong>Consejos para B&#250;squedas de  Encabezamientos M&#233;dicos (MeSH)</strong></p>
        <p>Buscar en los Encabezamientos de la Biblioteca Nacional de Medicina para temas medicinales.</p>
        <p><em>Ejemplos:</em></p>
        <ul>
          <li><em>Lung neoplasms</em></li>
          <li><em>Surgery oral</em></li>
          </ul>
        <p>Si su b&#250;squeda no tiene &#233;xito, pruebe una b&#250;squeda de palabra clave. </p>