        <form action="/search/" method="get" id="search" class="indexSearch" name="search">
        
        <div class="limits">
        <div class="limitColumn">
        <label> <input name="searchtype" class="searchtype" value="X" checked="checked" type="radio"> Keyword </label> 
        <label> <input name="searchtype" class="searchtype" value="t" type="radio"> Title begins with </label>
        </div>
        <div class="limitColumn">
        <label> <input name="searchtype" class="searchtype" value="s" type="radio"> Journal & Newspapers title begins with </label>
        <label> <input name="searchtype" class="searchtype" value="a" type="radio"> Author (last name first) </label>
        </div>
        </div>
        
        <div class="clear"></div>
        
<!--{nosort}-->
        
        <div class="searchBox"><input name="searcharg" value="" id="searcharg" class="text" type="text">
        
<!--{scope}-->
        
        
        <input value="Search" type="submit"> </label></div>
        
        </form>

        <p><strong>Search tips for Journal &amp; Newspaper Title begins with</strong></p>
        <p>Search for exact titles for journals, newspapers, or magazines. Enter words starting at the beginning of the title.</p>
        <p><em>Example:</em></p>
        <ul>
          <li><em>journal of management inquiry</em></li>
          </ul>
        <p>If your search is unsuccessful, try a keyword search. </p>