        <p><strong>&#23450;&#26399;&#25628;&#32034;</strong></p>
        <p>Search for exact titles for journals, newspapers, or magazines. Enter words starting at the beginning of the title.</p>
        <p><em>Example:</em></p>
        <ul>
          <li><em>journal of management inquiry</em></li>
          </ul>
        <p>&#22914;&#26524;&#26597;&#35810;&#22833;&#36133;, &#23581;&#35797;&#20851;&#38190;&#35789;&#25628;&#32034;. </p>