     <p><strong>This is a spanish test!!!!Search tips for Journal, Magazine, Newspaper Title begins with</strong></p>
        <p>Search for exact titles for journals, newspapers, or magazines. Enter words starting at the beginning of the title.</p>
        <p><em>Example:</em></p>
        <ul>
          <li><em>journal of management inquiry</em></li>
          </ul>
        <p>If your search is unsuccessful, try a Keyword search. </p>