          <p><strong>Search tips for Title begins with</strong></p>
        <p>Use this search if you have the title of the book, video, etc. Enter words starting at the beginnning of the title.  Exclude initial articles such as &quot;the&quot;, &quot;an&quot;, and &quot;de&quot; (German). </p>
        <p><em>Examples:</em></p>
        <ul>
          <li><em>Intruder in the Dust</em></li>
          <li><em>Adventures of Huckleberry Finn</em></li>
          </ul>