          <p><strong>Search Tips for Title begins with</strong></p>
        <p>Use this search if you have the title of the book, video, etc. Enter words starting at the beginnning of the title.  Exclude initial articles such as &quot;the&quot;, &quot;an&quot;, and &quot;de&quot; (German). </p>
        <p><em>Examples:</em></p>
        <ul>
          <li><em>Intruder in the Dust</em></li>
          <li><em>Adventures of Huckleberry Finn</em></li>
          </ul>
        <ul>
          <li><div class="tipLeft">science</div>Finds titles that begin with the word "science"</li>
          <li><div class="tipLeft">science|</div>Add a | (bar symbol) to find an exact match</li>
        </ul>
          
          <p>If your search is unsuccessful, try a Keyword search.</p>