        <form action="/search/" method="get" id="search" class="indexSearch" name="search">
        
        <div class="limits">
        <div class="limitColumn">
        <label> <input name="searchtype" class="searchtype" value="X" type="radio"> Keyword </label> 
        <label> <input name="searchtype" class="searchtype" value="t" checked="checked" type="radio"> Title begins with </label>
        </div>
        <div class="limitColumn">
        <label> <input name="searchtype" class="searchtype" value="s" type="radio"> Journal & Newspapers title begins with </label>
        <label> <input name="searchtype" class="searchtype" value="a" type="radio"> Author (last name first) </label>
        </div>
        </div>
        
        <div class="clear"></div>
        
<!--{nosort}-->
        
        <div class="searchBox"><input name="searcharg" value="" id="searcharg" class="text" type="text">
        
<!--{scope}-->
        
        
        <input value="Search" type="submit"> </label></div>
        
        </form>

          <p><strong>Search tips for Title begins with</strong></p>
        <p>Use this search if you have the title of the book, video, etc. Enter words starting at the beginnning of the title.  Exclude initial articles such as &quot;the&quot;, &quot;an&quot;, and &quot;de&quot; (German). </p>
        <p><em>Examples:</em></p>
        <ul>
          <li><em>Intruder in the Dust</em></li>
          <li><em>Adventures of Huckleberry Finn</em></li>
          </ul>