 <p><strong>&#26631;&#39064;&#25628;&#32034;</strong></p>
        <p>&#38543;&#24847;&#38190;&#20837;&#22810;&#25110;&#23569;&#30340;&#26631;&#39064;&#12290;&#20363;:</p>
        <ul>
          <li><em>Intruder in the Dust</em></li>
          <li><em>Adventures of Huckleberry Finn</em></li>
        </ul>
        <ul>
          <li><div class="tipLeft">science</div>Finds titles that begin with the word "science"</li>
          <li><div class="tipLeft">science|</div>Add a | (bar symbol) to find an exact match</li>
        </ul>
          
          <p>&#22914;&#26524;&#26597;&#35810;&#22833;&#36133;, &#23581;&#35797;&#20851;&#38190;&#35789;&#25628;&#32034;.</p>