          <p><strong>B&#250;squeda por t&#237;tulo</strong></p>
        <p>Indique el t&#237;tulo que quiere encontrar. </p>
        <p><em>Ejemplos:</em></p>
        <ul>
          <li><em>Intruder in the Dust</em></li>
          <li><em>Adventures of Huckleberry Finn</em></li>
        </ul>
        <ul>
          <li><div class="tipLeft">science</div>Finds titles that begin with the word "science"</li>
          <li><div class="tipLeft">science|</div>Add a | (bar symbol) to find an exact match</li>
        </ul>
          
          <p>Si su b&#250;squeda no tiene &#233;xito, pruebe una b&#250;squeda de palabra clave.</p>