        <p><strong>Search Tips for Genre/Form terms</strong></p>
        <p>The Genre/Form headings describes what a work is versus what it is about. Examples of genres are horror films, science fiction and thrillers. In the term Horror films "horror" is the genre and "films" is the form.</p>
	<p>Note that <strong>search results may not be comprehensive</strong> as Genre/Form headings are new to MERLIN.</p>
        <p><em>More examples of genre/form headings.</em></p>
        <ul>
          <li><em>Biography</em></li>
          <li><em>Western films</em></li>
        </ul> 
  <p>For a complete list of headings see our <a href="https://merlin.searchmobius.org/help#searching10">Help page</a></p>