        <p><strong>Search Tips for Genre/Form terms</strong></p>
        <p>The Genre/Form headings describes what a work is versus what it is about. Examples of genres are horror films, science fiction and thrillers. In the term Horror films "horror" is the genre and "films" is the form.</p>
    <p>Note that <strong>search results may not be comprehensive</strong> as Genre/Form headings are new to MERLIN.</p>
        <p>More examples of genre/form headings.</p>
            
            <div class="helpGenreLeft">   
                <ul>
                    <li><em>Almanacs</em></li>
                    <li><em>Anecdotes</em></li>
                    <li><em>Biography</em></li>
                    <li><em>Comic Books Strips Etc</em></li>
                    <li><em>Cookbooks</em></li>
                    <li><em>Documentary Films</em></li>
                    <li><em>Educational Films</em></li>
                    <li><em>Electronic Audio Files</em></li>
                    <li><em>Feature Films</em></li>
                    <li><em>Government Publications</em></li>
                    <li><em>Interviews</em></li>
                    <li><em>Maps</em></li>
                    <li><em>Motion pictures</em></li>
                    <li><em>Music Videos</em></li>
                    <li><em>Pamphlets</em></li>
                </ul>
            </div>
            <div class="helpGenreRight">
                <ul>                                    
                    <li><em>Plays</em></li>
                    <li><em>Poems</em></li>
                    <li><em>Poetry</em></li>
                    <li><em>Radio</em></li>
                    <li><em>Science Fiction</em></li>
                    <li><em>Sermons</em></li>
                    <li><em>Sonatas</em></li>
                    <li><em>Songs</em></li>
                    <li><em>Specifications</em></li>
                    <li><em>Statistics</em></li>
                    <li><em>Streaming audio</em></li>
                    <li><em>Topographic Maps</em></li>
                    <li><em>Video Recordings</em></li>
                    <li><em>Western films</em></li>                     
                </ul>
            </div>
