        <p><strong>&#20307;&#35009;/&#31867;&#22411;&#26597;&#35810;&#25552;&#31034;</strong></p>
        <p>&#20307;&#35009;/&#31867;&#22411;&#26631;&#39064;&#25551;&#36848;&#20107;&#29289;&#30340;&#23646;&#24615;, &#32780;&#19981;&#26159;&#20854;&#20869;&#23481;, &#20363;&#22914;: &#24656;&#24598;&#24433;&#29255;, &#20256;&#35760;, &#22320;&#22270;.</p>
    <p>&#27880;: &#20307;&#35009;/&#31867;&#22411;&#26631;&#39064;&#26597;&#35810;&#23545;MERLIN&#31995;&#32479;&#26159;&#26032;&#20107;&#29289;, &#30446;&#21069;&#20854;&#26597;&#35810;&#32467;&#26524;&#21487;&#33021;&#19981;&#26159;&#24456;&#20840;&#38754;.</p>
        <p>&#26356;&#22810;&#20307;&#35009;/&#31867;&#22411;&#26631;&#39064;&#22914;&#19979;:</p>
            
            <div class="helpGenreLeft">   
                <ul>
                    <li><em>Almanacs</em></li>
                    <li><em>Anecdotes</em></li>
                    <li><em>Biography</em></li>
                    <li><em>Comic Books Strips Etc</em></li>
                    <li><em>Cookbooks</em></li>
                    <li><em>Documentary Films</em></li>
                    <li><em>Educational Films</em></li>
                    <li><em>Electronic Audio Files</em></li>
                    <li><em>Feature Films</em></li>
                    <li><em>Government Publications</em></li>
                    <li><em>Interviews</em></li>
                    <li><em>Maps</em></li>
                    <li><em>Motion pictures</em></li>
                    <li><em>Music Videos</em></li>
                    <li><em>Pamphlets</em></li>
                </ul>
            </div>
            <div class="helpGenreRight">
                <ul>                                    
                    <li><em>Plays</em></li>
                    <li><em>Poems</em></li>
                    <li><em>Poetry</em></li>
                    <li><em>Radio</em></li>
                    <li><em>Science Fiction</em></li>
                    <li><em>Sermons</em></li>
                    <li><em>Sonatas</em></li>
                    <li><em>Songs</em></li>
                    <li><em>Specifications</em></li>
                    <li><em>Statistics</em></li>
                    <li><em>Streaming audio</em></li>
                    <li><em>Topographic Maps</em></li>
                    <li><em>Video Recordings</em></li>
                    <li><em>Western films</em></li>                     
                </ul>
            </div>
