        <p><strong>Consejos sobre t&#233;rminos en b&#250;squedas por G&#233;nero/Formato</strong></p>
        <p>Encabezamientos de G&#233;nero/Formato describen el tipo de una obra, no de lo que se trata. Por ejemplo: biograf&#237;a, mapas o pel&#237;culas de terror</p>
    <p>Por favor tome nota de que los resultados de una <strong>b&#250;squeda no siempre se&#241;alan la totalidad</strong> porque los encabezamientos de G&#233;nero/Formato son nuevos para Merlin.</p>
        <p>M&#225;s ejemplos de encabezamientos de G&#233;nero/Formato.</p>
            
            <div class="helpGenreLeft">   
                <ul>
                    <li><em>Almanacs</em></li>
                    <li><em>Anecdotes</em></li>
                    <li><em>Biography</em></li>
                    <li><em>Comic Books Strips Etc</em></li>
                    <li><em>Cookbooks</em></li>
                    <li><em>Documentary Films</em></li>
                    <li><em>Educational Films</em></li>
                    <li><em>Electronic Audio Files</em></li>
                    <li><em>Feature Films</em></li>
                    <li><em>Government Publications</em></li>
                    <li><em>Interviews</em></li>
                    <li><em>Maps</em></li>
                    <li><em>Motion pictures</em></li>
                    <li><em>Music Videos</em></li>
                    <li><em>Pamphlets</em></li>
                </ul>
            </div>
            <div class="helpGenreRight">
                <ul>                                    
                    <li><em>Plays</em></li>
                    <li><em>Poems</em></li>
                    <li><em>Poetry</em></li>
                    <li><em>Radio</em></li>
                    <li><em>Science Fiction</em></li>
                    <li><em>Sermons</em></li>
                    <li><em>Sonatas</em></li>
                    <li><em>Songs</em></li>
                    <li><em>Specifications</em></li>
                    <li><em>Statistics</em></li>
                    <li><em>Streaming audio</em></li>
                    <li><em>Topographic Maps</em></li>
                    <li><em>Video Recordings</em></li>
                    <li><em>Western films</em></li>                     
                </ul>
            </div>